version: '3.8'

services:
  app:
    build: .
    container_name: my-app
    ports:
      - "8080:8080"
    environment:
      - POSTGRESQL_HOST=db
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DATABASE=websec
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=keppi
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: websec
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: keppi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: